### ISSUE TITLE
Debond Application EPIC

### ISSUE THREAD

**Issue by dhruvmalik007** [Debond-Protocol/EIP-3475#72]
This epic will be eventually converted to each of the corresponding tickets, 

## Universal (@meriemmarsli):
- [ ] Standardize all X & Y positions, spacing, etc.
- [ ] Review the spacing left for elements after we expand & collapse the side menu
__________________________

Local Components (@nnevena93):
- [ ] Add blue hover to all tab components
__________________________

## Dashboard to-do (@meriemmarsli & @nnevena93):
- [ ] swap the graphs to the updated version
- [ ]update text copy for the gamified steps (need Yu here)
- [ ]content of the graphs to check with devs and Yu
- [ ]check if all universal components are the current versions
- [ ]swap bond components to the current version
- [ ]swap the “4.Bond-desktop” to the updated version (get it from the bonds page
- [ ]swap the pop-up “place a bid” for the pop-up for bonds
- [ ]make sure all the pop-up flows follow the established protocols created in the “local components”
- [ ]create a user flow for this page

@yuliu-debond , to help improve the workflow, we would need you to:
- [ ]Delete all pages & designs from the Dashboard that are redundant, expired, or unnecessary (since you have created several versions so far).
- [ ]Check the content of the graphs with devs (we have a placeholder design).
- [ ]Let me know (Nevena) if the graph redesign is satisfactory. I tagged you in a comment a couple of days ago.
- [ ]Let us know what we should write in the gamified steps where you were tagged (the explanation you provided wasn’t enough).
__________________________

## Bonds to-do (@meriemmarsli & Nevena):
- [ ]check if all universal components are the current versions
- [ ]button text to reflect the tab open (if you are staking a bond, it should say “Stake Bond” on the button; if you’re buying, the same logic)
- [ ]to review the design of the bonds details section w/ Nevena for possibly adding a more horizontal layout with scroll (see image 1 in Figma)
- [ ]what are the pop-ups for the bonds page?
- [ ]text copy for the gamified steps
- [ ]modify titles and checkmarks for the gamified steps
- [ ]create user flow for this page

@YS_1984, to help improve the workflow, we would need you to:
- [ ]Delete all pages & designs from the Bonds that are redundant, expired, or unnecessary (since you have created several versions so far).
- [ ]Let us know what we should write in the gamified steps where you were tagged (the explanation you provided wasn’t enough).
- [ ]Please let us know what are the pop-ups for the Bonds page? Can't find adeqaute ones anywhere.
__________________________

## Bond Exchange to-do (@meriemmarsli & Nevena):
- [ ]check if all universal components are the current versions (leave comments on components that need to be swapped, tag eachother)
- [ ]design withdraw and cancel flow in “your auctions”. This is in case nobody placed a bid on the user’s auction, or the user decided to
- [ ]cancel it before the auction ended. They need this step to get back their bonds.
- [ ]modify titles and checkmarks for the gamified steps 
- [ ]create user flow for this page

@YS_1984, to help improve the workflow, we would need you to:
- [ ]Delete all pages & designs from the Bond Exchange that are redundant, expired, or unnecessary (since you have created several versions so far).
- [ ]Let us know what we should write in the gamified steps where you were tagged (the explanation you provided wasn’t enough).
__________________________

Swap to-do (@meriemmarsli & Nevena):
- [ ]check if all universal components are the current versions (leave comments on components that need to be swapped, tag each other)
- [ ]fix design issues (overlapping of elements etc)
- [ ]swap pop up redundant, pls remove
- [ ]update wallet pop up to the current version
- [ ]add slippage (ask Nevena about this, she designed it before, it’s already done)
- [ ]modify titles and checkmarks for the gamified steps
- [ ] create user flow for this page.

@yuliu-debond, to help improve the workflow, we would need you to:
- [ ] Delete all pages & designs from the Swap that are redundant, expired, or unnecessary (since you have created several versions so far).
- [ ] Let us know what we should write in the gamified steps where you were tagged (the explanation you provided wasn’t enough).

## Governance Ops to-do (@meriemmarsli & Nevena):
- [ ] check if all universal components are the current versions (leave comments on components that need to be swapped, tag eachother) and create the right components.
- [ ] design multiple votes pop-up. This is when the user wants to vote on a proposal and needs to add the amount of votes they are dedicating to the proposal
- [ ] rethink w/ Nevena about the design of the “Convert DGOV to vote”. We have too many tabs (plus tab for “all my stakings” and “stake dgov to vote”. Let’s rethink the layout.
- [ ] For “all my stakings”, copy the format of the row from Bond Exchange. Add button “Unstake”
- [ ] pop up for creating a proposal
- [ ] pop up for voting for/against a proposal
- [ ] modify titles and checkmarks for the gamified steps
- [ ] create user flow for this page

@YS_1984, to help improve the workflow, we would need you to:
- [ ] Delete all pages & designs from the Governance that are redundant, expired, or unnecessary (since you have created several versions so far).
- [ ] Let us know what we should write in the gamified steps where you were tagged (the explanation you provided wasn’t enough).
- [ ] Let us know if this page requires any custom pop-ups
__________________________

Bond Wallet Ops to-do (@meriemmarsli & Nevena):
- [ ] check if all universal components are the current versions (leave comments on components that need to be swapped, tag eachother)
- [ ] check for the bond wallet dropdown component - where is it, should we design it etc
- [ ] update text on the pop ups
- [ ] update bond page on bond wallet
- [ ] review if the wallet dropdown needs any touchups
- [ ] modify titles and checkmarks for the gamified steps
- [ ] in gamified steps, flip text to properly fit CTAs (first should be select and then redeem/transfer)
- [ ] create user flow for this page

@yuliu-debond , to help improve the workflow, we would need you to:
- [ ] Delete all pages & designs from the Governance that are redundant, expired, or unnecessary (since you have created several versions so far).
- [ ] Let us know what we should write in the gamified steps where you were tagged (the explanation you provided wasn’t enough).

**Comment by nnevena93** [comment]
Hey @dhruvmalik007, I can comment but can't checkmarks
